In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
from gympy.layers import Linear, Relu, Sigmoid, relu, sigmoid, linear, tanh, Tanh, Softmax


In [2]:
bias = np.zeros(5)
x, y, w = make_regression(
    n_samples=10,
    n_features=3,
    n_informative=3,
    n_targets=5,
    noise=20,
    coef=True,
    random_state=21,
    bias=bias)

print(f'x {x.shape}')
print(f'y {y.shape}')
print(f'w {w.shape}')
print(f'b {bias.shape}')
w


x (10, 3)
y (10, 5)
w (3, 5)
b (5,)


array([[60.03692654, 89.83403386, 49.0032225 , 82.83181322, 85.88894712],
       [61.48247111, 65.27560732, 38.68164341, 41.03541786, 81.01575495],
       [78.84451436, 88.76554372, 69.8860789 , 45.43903076, 30.59151648]])

In [3]:
w

array([[60.03692654, 89.83403386, 49.0032225 , 82.83181322, 85.88894712],
       [61.48247111, 65.27560732, 38.68164341, 41.03541786, 81.01575495],
       [78.84451436, 88.76554372, 69.8860789 , 45.43903076, 30.59151648]])

In [4]:
z = np.matmul(w.T, x.T) + bias.reshape(-1, 1)
z_relu = relu(z)
z_sigmoid = sigmoid(z)
z_tanh = tanh(z)

In [5]:
z_relu

array([[112.22300951,   2.47639432,  79.50090154,   0.        ,
          0.        ,  72.26920311,   0.        ,   0.        ,
         62.20797899,  70.71686737],
       [104.66130818,   8.1659445 ,  75.82341292,   0.        ,
          0.        ,  79.09447162,   0.        ,   0.        ,
         65.62991159,  66.02578459],
       [ 76.89724587,   8.59819164,  58.94603243,   0.        ,
          0.        ,  65.34806593,   0.        ,   0.        ,
         59.38364187,  65.46452021],
       [ 40.45804426,   6.74675243,  28.2107279 ,   0.        ,
          0.        ,  35.99529163,   0.        ,   0.        ,
         23.3840756 ,  11.10847116],
       [ 92.48563624,   0.        ,  50.50897366,   0.        ,
          0.        ,  18.10970935,   0.        ,   0.        ,
          0.        ,   0.        ]])

In [6]:
bias.reshape(-1, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [7]:
zlin = Linear(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1)
)
zlin.forward(x.T) == z

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [ ]:
zrelu = Relu(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1)
)
zrelu.forward(x.T) == z_relu

In [ ]:
zsig = Sigmoid(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1)
)
zsig.forward(x.T) == z_sigmoid

In [ ]:
ztanh = Tanh(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1)
)
ztanh.forward(x.T) == z_tanh

In [ ]:
zlin = Linear(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1),
    dropout_rate=0.5
)
dp = zlin.dropout_array()
dp_arr = dp * zlin.forward(x.T[:,:5])

In [ ]:
from gympy.layers import softmax_derivative, softmax

In [ ]:
 x = np.array([1, 2]).T
 softmax(x)

In [ ]:
softmax_derivative(x)

In [ ]:

zsof = Softmax(
    n_input=3,
    n_output=5
)

zsof.forward(x.T[:,:5]).shape

In [ ]:
zsof.derivative()