In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.datasets import make_regression
from gympy.layers import Linear, Relu, Sigmoid, relu, sigmoid, linear, tanh, Tanh


In [2]:
bias = np.zeros(5)
x, y, w = make_regression(
    n_samples=10,
    n_features=3,
    n_informative=3,
    n_targets=5,
    noise=20,
    coef=True,
    random_state=21,
    bias=bias)

print(f'x {x.shape}')
print(f'y {y.shape}')
print(f'w {w.shape}')
print(f'b {bias.shape}')
w


x (10, 3)
y (10, 5)
w (3, 5)
b (5,)


array([[60.03692654, 89.83403386, 49.0032225 , 82.83181322, 85.88894712],
       [61.48247111, 65.27560732, 38.68164341, 41.03541786, 81.01575495],
       [78.84451436, 88.76554372, 69.8860789 , 45.43903076, 30.59151648]])

In [3]:
z = np.matmul(w.T, x.T) + bias.reshape(-1, 1)
z_relu = relu(z)
z_sigmoid = sigmoid(z)
z_tanh = tanh(z)

In [4]:
bias.reshape(-1, 1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [5]:
zlin = Linear(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1)
)
zlin.forward(x.T) == z

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [6]:
zrelu = Relu(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1)
)
zrelu.forward(x.T) == z_relu

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [7]:
zsig = Sigmoid(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1)
)
zsig.forward(x.T) == z_sigmoid

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [10]:
ztanh = Tanh(
    n_input=3,
    n_output=5,
    weights=w.T,
    bias=bias.reshape(-1,1)
)
ztanh.forward(x.T) == z_tanh

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])